name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: apt-get install cowsay
      - run: ls -l
      - run: cat README.md
      - run: cat README.md | cowsay